doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
            aion:
                # configure these for your database server
                url: '%env(DATABASE_AION_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
            aiongs:
                # configure these for your database server
                url: '%env(DATABASE_AIONGS_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
            maxsuport:
                # configure these for your database server
                url: '%env(DATABASE_AIONLS_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
            

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '5.6'

    orm:
        auto_generate_proxy_classes: true
        # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            aion:
                connection: aion
                mappings:
                    Aion:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Aion
            aiongs:
                connection: aiongs
                mappings:
                    Aion:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Aiongs
            maxsuport:
                connection: maxsuport
                mappings:
                    Aion:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Maxsuport
            
        # mappings:
        #     App:
        #         is_bundle: false
        #         type: annotation
        #         dir: '%kernel.project_dir%/src/Entity'
        #         prefix: 'App\Entity'
        #         alias: App
